name: Manual workflow

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input your parameter here'
        default: 'Hello from Andrey Ulrikh ;)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  homework:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: echo "${{ github.event.inputs.name }}" >output.txt && date >>output.txt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: output.txt
